#!/bin/bash
#SBATCH --job-name="ml"
#SBATCH --partition=rtx2080ti
#SBATCH --ntasks=2
#SBATCH --gres=gpu:1
#SBATCH --time=0-10:10
#SBATCH --output=cout.txt
#SBATCH --error=cerr.txt
###SBATCH --test-only
sbatch_pre.sh
module load gcc/8.3.0 cuda/11.0 python/3.8.7-gnu-gpu
python3 train.py Quaternion
python3 train.py Error
python3 train.py Bands
python3 train.py BS
python3 train.py BC
python3 train.py MAD
python3 train.py Phase
python3 train.py Error_Quaternion
python3 train.py Bands_Quaternion
python3 train.py Bands_Error
python3 train.py BS_Quaternion
python3 train.py BS_Error
python3 train.py BS_Bands
python3 train.py BC_Quaternion
python3 train.py BC_Error
python3 train.py BC_Bands
python3 train.py BC_BS
python3 train.py MAD_Quaternion
python3 train.py MAD_Error
python3 train.py MAD_Bands
python3 train.py MAD_BS
python3 train.py MAD_BC
python3 train.py Phase_Quaternion
python3 train.py Phase_Error
python3 train.py Phase_Bands
python3 train.py Phase_BS
python3 train.py Phase_BC
python3 train.py Phase_MAD
python3 train.py Bands_Error_Quaternion
python3 train.py BS_Error_Quaternion
python3 train.py BS_Bands_Quaternion
python3 train.py BS_Bands_Error
python3 train.py BC_Error_Quaternion
python3 train.py BC_Bands_Quaternion
python3 train.py BC_Bands_Error
python3 train.py BC_BS_Quaternion
python3 train.py BC_BS_Error
python3 train.py BC_BS_Bands
python3 train.py MAD_Error_Quaternion
python3 train.py MAD_Bands_Quaternion
python3 train.py MAD_Bands_Error
python3 train.py MAD_BS_Quaternion
python3 train.py MAD_BS_Error
python3 train.py MAD_BS_Bands
python3 train.py MAD_BC_Quaternion
python3 train.py MAD_BC_Error
python3 train.py MAD_BC_Bands
python3 train.py MAD_BC_BS
python3 train.py Phase_Error_Quaternion
python3 train.py Phase_Bands_Quaternion
python3 train.py Phase_Bands_Error
python3 train.py Phase_BS_Quaternion
python3 train.py Phase_BS_Error
python3 train.py Phase_BS_Bands
python3 train.py Phase_BC_Quaternion
python3 train.py Phase_BC_Error
python3 train.py Phase_BC_Bands
python3 train.py Phase_BC_BS
python3 train.py Phase_MAD_Quaternion
python3 train.py Phase_MAD_Error
python3 train.py Phase_MAD_Bands
python3 train.py Phase_MAD_BS
python3 train.py Phase_MAD_BC
python3 train.py BS_Bands_Error_Quaternion
python3 train.py BC_Bands_Error_Quaternion
python3 train.py BC_BS_Error_Quaternion
python3 train.py BC_BS_Bands_Quaternion
python3 train.py BC_BS_Bands_Error
python3 train.py MAD_Bands_Error_Quaternion
python3 train.py MAD_BS_Error_Quaternion
python3 train.py MAD_BS_Bands_Quaternion
python3 train.py MAD_BS_Bands_Error
python3 train.py MAD_BC_Error_Quaternion
python3 train.py MAD_BC_Bands_Quaternion
python3 train.py MAD_BC_Bands_Error
python3 train.py MAD_BC_BS_Quaternion
python3 train.py MAD_BC_BS_Error
python3 train.py MAD_BC_BS_Bands
python3 train.py Phase_Bands_Error_Quaternion
python3 train.py Phase_BS_Error_Quaternion
python3 train.py Phase_BS_Bands_Quaternion
python3 train.py Phase_BS_Bands_Error
python3 train.py Phase_BC_Error_Quaternion
python3 train.py Phase_BC_Bands_Quaternion
python3 train.py Phase_BC_Bands_Error
python3 train.py Phase_BC_BS_Quaternion
python3 train.py Phase_BC_BS_Error
python3 train.py Phase_BC_BS_Bands
python3 train.py Phase_MAD_Error_Quaternion
python3 train.py Phase_MAD_Bands_Quaternion
python3 train.py Phase_MAD_Bands_Error
python3 train.py Phase_MAD_BS_Quaternion
python3 train.py Phase_MAD_BS_Error
python3 train.py Phase_MAD_BS_Bands
python3 train.py Phase_MAD_BC_Quaternion
python3 train.py Phase_MAD_BC_Error
python3 train.py Phase_MAD_BC_Bands
python3 train.py Phase_MAD_BC_BS
python3 train.py BC_BS_Bands_Error_Quaternion
python3 train.py MAD_BS_Bands_Error_Quaternion
python3 train.py MAD_BC_Bands_Error_Quaternion
python3 train.py MAD_BC_BS_Error_Quaternion
python3 train.py MAD_BC_BS_Bands_Quaternion
python3 train.py MAD_BC_BS_Bands_Error
python3 train.py Phase_BS_Bands_Error_Quaternion
python3 train.py Phase_BC_Bands_Error_Quaternion
python3 train.py Phase_BC_BS_Error_Quaternion
python3 train.py Phase_BC_BS_Bands_Quaternion
python3 train.py Phase_BC_BS_Bands_Error
python3 train.py Phase_MAD_Bands_Error_Quaternion
python3 train.py Phase_MAD_BS_Error_Quaternion
python3 train.py Phase_MAD_BS_Bands_Quaternion
python3 train.py Phase_MAD_BS_Bands_Error
python3 train.py Phase_MAD_BC_Error_Quaternion
python3 train.py Phase_MAD_BC_Bands_Quaternion
python3 train.py Phase_MAD_BC_Bands_Error
python3 train.py Phase_MAD_BC_BS_Quaternion
python3 train.py Phase_MAD_BC_BS_Error
python3 train.py Phase_MAD_BC_BS_Bands
python3 train.py MAD_BC_BS_Bands_Error_Quaternion
python3 train.py Phase_BC_BS_Bands_Error_Quaternion
python3 train.py Phase_MAD_BS_Bands_Error_Quaternion
python3 train.py Phase_MAD_BC_Bands_Error_Quaternion
python3 train.py Phase_MAD_BC_BS_Error_Quaternion
python3 train.py Phase_MAD_BC_BS_Bands_Quaternion
python3 train.py Phase_MAD_BC_BS_Bands_Error
python3 train.py Phase_MAD_BC_BS_Bands_Error_Quaternion
sbatch_post.sh